// GENERATED by Tools/gen_look_shared.py from Scripts/make_ground_material.py SCALARS (RockCos, RockBand). Do not edit by hand:
// test_scatter_constants.py regenerates this file and diffs it, so a change of the ground's rock edge fails a test until it is regenerated.
// Thresholds are tan^2(slope) * 2^32 = (1 / c^2 - 1) * 2^32 for the cosine c, so no float constant ever decides a scatter rule.
#pragma once

#include "CoreMinimal.h"

namespace ChimeraTerrain
{
	namespace LookShared
	{
		/** The material's RockCos and RockBand in Q16 (text values 0.8192 and 0.10). */
		constexpr int64 RockCosQ16 = 53687;
		constexpr int64 RockBandQ16 = 6554;
		/** Slope threshold for c = RockCos (35.00 deg). */
		constexpr int64 RockSlopeThr = 2105032704ll;
		/** Lower edge of the material's rock band, c = RockCos + RockBand (23.19 deg). */
		constexpr int64 RockBandLoThr = 788263515ll;
		/** Upper edge of the material's rock band, c = RockCos - RockBand (44.01 deg). */
		constexpr int64 RockBandHiThr = 4008519584ll;
	}
}
