"""Generate Source/ChimeraTerrain/Data/TerrainLookShared.h from Scripts/make_ground_material.py SCALARS (plan C scatter 3.1, task S2).

The scatter generator must agree with the ground material about where rock begins, but it must never depend on compiler float constants
(plan C scatter 3.3, F12). So the material's RockCos and RockBand are turned here into integer slope thresholds
    thr(c) = round((1 / c^2 - 1) * 2^32)          (tan^2 of the slope angle whose cosine is c, in Q32)
for c = RockCos and RockCos +- RockBand, and written as literals. test_scatter_constants.py regenerates the header and diffs it against the
checked-in file, so the thresholds follow the material and any later drift fails a test (plan C scatter risk 16).

Usage:  python gen_look_shared.py            rewrite the header
        python gen_look_shared.py --check    exit 1 when the checked-in header differs from a fresh generation
        python gen_look_shared.py --print    print the generated text
The material script imports `unreal`, so SCALARS is read with ast (the file is never executed).
"""
import ast
import math
import os
import sys
from fractions import Fraction

T = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MATERIAL = os.path.join(T, "Scripts", "make_ground_material.py")
HEADER = os.path.join(T, "Source", "ChimeraTerrain", "Data", "TerrainLookShared.h")


def read_scalars(path=MATERIAL):
    """The SCALARS list of make_ground_material.py as {name: value-text}, read with ast (values kept as exact decimal strings)."""
    with open(path, "r", encoding="utf-8") as f:
        src = f.read()
    tree = ast.parse(src)
    for node in tree.body:
        if isinstance(node, ast.Assign) and any(isinstance(t, ast.Name) and t.id == "SCALARS" for t in node.targets):
            out = {}
            for elt in node.value.elts:
                name = elt.elts[0].value
                seg = ast.get_source_segment(src, elt.elts[1])
                out[name] = seg
            return out
    raise SystemExit("SCALARS not found in " + path)


def thr(c):
    """tan^2(acos(c)) * 2^32 as an integer, exact rational arithmetic on the decimal text of c."""
    f = Fraction(c)
    return int(round((1 / (f * f) - 1) * 2 ** 32))


def q16(x):
    """round(x * 65536) with the same rule as the C++ ScQ (v * 65536 + 0.5, truncated)."""
    return int(Fraction(x) * 65536 + Fraction(1, 2))


def generate():
    sc = read_scalars()
    cos_text = sc["RockCos"]
    band_text = sc["RockBand"]
    cos = Fraction(cos_text)
    band = Fraction(band_text)
    lo_c = cos + band   # larger cosine = shallower slope = the band's lower edge
    hi_c = cos - band
    deg = lambda c: math.degrees(math.acos(float(c)))
    lines = [
        "// GENERATED by Tools/gen_look_shared.py from Scripts/make_ground_material.py SCALARS (RockCos, RockBand). Do not edit by hand:",
        "// test_scatter_constants.py regenerates this file and diffs it, so a change of the ground's rock edge fails a test until it is regenerated.",
        "// Thresholds are tan^2(slope) * 2^32 = (1 / c^2 - 1) * 2^32 for the cosine c, so no float constant ever decides a scatter rule.",
        "#pragma once",
        "",
        "#include \"CoreMinimal.h\"",
        "",
        "namespace ChimeraTerrain",
        "{",
        "	namespace LookShared",
        "	{",
        "		/** The material's RockCos and RockBand in Q16 (text values %s and %s). */" % (cos_text, band_text),
        "		constexpr int64 RockCosQ16 = %d;" % q16(cos),
        "		constexpr int64 RockBandQ16 = %d;" % q16(band),
        "		/** Slope threshold for c = RockCos (%.2f deg). */" % deg(cos),
        "		constexpr int64 RockSlopeThr = %dll;" % thr(cos),
        "		/** Lower edge of the material's rock band, c = RockCos + RockBand (%.2f deg). */" % deg(lo_c),
        "		constexpr int64 RockBandLoThr = %dll;" % thr(lo_c),
        "		/** Upper edge of the material's rock band, c = RockCos - RockBand (%.2f deg). */" % deg(hi_c),
        "		constexpr int64 RockBandHiThr = %dll;" % thr(hi_c),
        "	}",
        "}",
        "",
    ]
    return "\n".join(lines)


def main():
    text = generate()
    if "--print" in sys.argv:
        sys.stdout.write(text)
        return 0
    if "--check" in sys.argv:
        try:
            with open(HEADER, "r", encoding="utf-8", newline="") as f:
                cur = f.read()
        except OSError:
            print("MISSING " + HEADER)
            return 1
        if cur.replace("\r\n", "\n") != text:
            print("LOOKSHARED STALE: regenerate with python Tools/gen_look_shared.py")
            return 1
        print("LOOKSHARED OK")
        return 0
    with open(HEADER, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    print("wrote " + HEADER)
    return 0


if __name__ == "__main__":
    sys.exit(main())
