<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <NoWarn>$(NoWarn);CS8618;CS8604;CS8625;CS8765;CS0618</NoWarn>
    <LangVersion>latest</LangVersion><EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles><CompilerGeneratedFilesOutputPath>gen</CompilerGeneratedFilesOutputPath>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
  </PropertyGroup>
  <Import Project="D:\Projects\Project_Chimera\godot\SimSources.props" />
  <ItemGroup>
    <Compile Include="*.cs" />
  </ItemGroup>
</Project>
