#nullable enable
using System.Linq;
using ProjectChimera.Core;
using Xunit;

namespace ProjectChimera.Sim.Tests.Golden
{
    /// <summary>
    /// Migration Step 1 — the golden-checksum replay regression guard the entire strangler rides on.
    /// Runs the fixed in-code scenario (<see cref="GoldenScenario"/>) through the real 9-system
    /// <see cref="SimulationLoop"/> and asserts the per-tick <see cref="SimChecksum"/> sequence is
    /// deterministic in-process (AC1), reproduces the committed golden produced by a prior process (AC2),
    /// and that a one-tick perturbation is detected AND located (AC3).
    ///
    /// Uses today's SimChecksum AS-IS (Ore[P1]/Ore[P2] only — a known-narrow hash). Story 1.3b widens
    /// coverage and re-baselines the golden once via the env-var record path.
    /// </summary>
    public class GoldenChecksumReplayTests
    {
        /// <summary>
        /// Records the golden sequence and, in re-baseline mode (CHIMERA_GOLDEN_RECORD=1), writes it to the
        /// source file under Golden/. In normal mode it does NOT write — it only verifies the harness emits
        /// the expected number of samples and that the sequence actually evolves over time (a constant
        /// sequence would mean the scenario isn't exercising the systems).
        ///
        /// Re-baseline (intentional behavior change only):
        ///   PowerShell: $env:CHIMERA_GOLDEN_RECORD=1; dotnet test godot/ProjectChimera.Sim.Tests --filter FullyQualifiedName~Golden; Remove-Item Env:\CHIMERA_GOLDEN_RECORD
        ///   bash:       CHIMERA_GOLDEN_RECORD=1 dotnet test godot/ProjectChimera.Sim.Tests --filter FullyQualifiedName~Golden
        ///   then: dotnet build (refreshes the embedded copy); git add the golden; commit.
        /// </summary>
        [Fact]
        public void RecordGoldenBaseline()
        {
            var seq = GoldenChecksumReplay.RunAndRecord(GoldenScenario.DefaultTicks);

            // The harness must emit one sample per tick (ChecksumInterval = 1).
            Assert.True(seq.Count >= GoldenScenario.DefaultTicks,
                $"Expected >= {GoldenScenario.DefaultTicks} checksum samples, got {seq.Count}.");

            // The sequence must CHANGE over time — proves the scenario is dynamic, not a static constant.
            // (If this fails, fix the scenario so units actually move/fight/gather — never "fix" the golden.)
            Assert.True(seq.Select(s => s.Hash).Distinct().Count() > 1,
                "Golden sequence is constant — the scenario is not exercising the systems.");

            // Re-baseline safety gate: in record mode the 3 AC tests early-return, so this is the ONLY body
            // that runs. Never commit a golden a second in-process run can't reproduce, or one ParseGolden
            // can't read back — catch nondeterminism / format breakage AT record time, not on the next CI run.
            var seq2 = GoldenChecksumReplay.RunAndRecord(GoldenScenario.DefaultTicks);
            Assert.True(seq.SequenceEqual(seq2),
                "Refusing to record: two in-process runs diverged — fix the nondeterminism before re-baselining.");
            Assert.True(
                GoldenChecksumReplay.ParseGolden(
                    System.Text.Encoding.UTF8.GetBytes(GoldenChecksumReplay.FormatGolden(seq)))
                    .SequenceEqual(seq),
                "Refusing to record: FormatGolden/ParseGolden do not round-trip the recorded sequence.");

            bool wrote = GoldenChecksumReplay.MaybeRecord(seq);
            if (wrote)
                Assert.True(GoldenChecksumReplay.IsRecordMode); // sanity: only writes in record mode
        }

        /// <summary>
        /// AC1 — in-process determinism + golden match. Two FRESH builds in one process produce
        /// byte-identical sequences (proving no static/shared mutable state leaks between runs), and both
        /// match the committed golden.
        /// </summary>
        [Fact]
        public void RunsTwiceInProcess_BothMatchGoldenAndEachOther()
        {
            if (GoldenChecksumReplay.IsRecordMode) return; // re-baseline run: golden is being rewritten; skip

            var seq1 = GoldenChecksumReplay.RunAndRecord(GoldenScenario.DefaultTicks);
            var seq2 = GoldenChecksumReplay.RunAndRecord(GoldenScenario.DefaultTicks);

            Assert.True(seq1.SequenceEqual(seq2),
                "Two in-process runs diverged — a static/shared mutable-state leak broke determinism.");

            var golden = GoldenChecksumReplay.LoadGolden();
            var div = GoldenChecksumReplay.CompareSequences(golden, seq1);
            Assert.True(div is null, div is null ? "" : GoldenChecksumReplay.DescribeDivergence(div.Value));
        }

        /// <summary>
        /// AC2 — no static/mutable-state leakage across processes. The committed golden was generated by a
        /// PRIOR process invocation (the record run / re-baseline) and embedded at build time, so asserting
        /// a fresh `dotnet test` process's run against it IS the two-process comparison — no subprocess
        /// spawner needed. Together with AC1's in-process equality this fully covers "no leakage between runs".
        /// </summary>
        [Fact]
        public void MatchesGolden_RecordedInSeparateProcess()
        {
            if (GoldenChecksumReplay.IsRecordMode) return; // re-baseline run: golden is being rewritten; skip

            var seq = GoldenChecksumReplay.RunAndRecord(GoldenScenario.DefaultTicks);
            var golden = GoldenChecksumReplay.LoadGolden();

            var div = GoldenChecksumReplay.CompareSequences(golden, seq);
            Assert.True(div is null, div is null ? "" : GoldenChecksumReplay.DescribeDivergence(div.Value));
        }

        /// <summary>
        /// AC3 — drift is detected AND located. Injecting +1 raw into the worker's Fixed health at loop
        /// index K (a non-combat unit, so the change persists) must make the harness FAIL with a divergence
        /// located at exactly tick K+1 (the perturb hook runs before StepOnce), with expected != actual.
        /// Proves the guard actually guards and points at the exact tick.
        /// </summary>
        [Fact]
        public void OneTickPerturbation_IsDetectedAndLocated()
        {
            if (GoldenChecksumReplay.IsRecordMode) return; // re-baseline run: skip

            const int k = 100;                              // perturb at loop index 100 => tick 101
            // Precondition: the run must extend past the perturbed tick, or "located at K+1" is unprovable.
            // Guards a future re-baseline that shortens DefaultTicks from silently turning this into a
            // confusing "perturbation went undetected" false-fail.
            Assert.True(GoldenScenario.DefaultTicks > k + 1,
                $"AC3 needs DefaultTicks ({GoldenScenario.DefaultTicks}) > k+1 ({k + 1}) so the perturbed tick is recorded.");
            int targetId = GoldenScenario.PerturbTargetId;  // the worker — combat never overwrites its health

            var golden = GoldenChecksumReplay.LoadGolden();
            var perturbed = GoldenChecksumReplay.RunAndRecord(GoldenScenario.DefaultTicks,
                perturb: (i, w) =>
                {
                    if (i == k)
                        w.Health[targetId] = Fixed.FromRaw(w.Health[targetId].Raw + 1);
                });

            var div = GoldenChecksumReplay.CompareSequences(golden, perturbed);

            Assert.True(div is not null, "Perturbation went undetected — the guard does not actually guard!");
            Assert.Equal((uint)(k + 1), div!.Value.Tick);
            Assert.NotEqual(div.Value.Expected, div.Value.Actual);
        }
    }
}
