#nullable enable
using System.Linq;
using Xunit;

namespace ProjectChimera.Sim.Tests.Golden
{
    /// <summary>
    /// Story 1.8b (AC5, D7) — the applier-DRIVEN golden regression guard (realizes <see cref="GoldenScenario"/>'s
    /// <c>TODO(1.8b)</c>). Runs an alpha_map_01-mirroring <see cref="ProjectChimera.Core.Definitions.ScenarioData"/>
    /// through the validator and the Godot-free <see cref="ProjectChimera.Core.Sim.ScenarioApplier"/>, then pins the
    /// per-tick SimChecksum sequence — so the applier's deterministic output is regression-guarded exactly like the
    /// hand-populated <see cref="GoldenScenario"/>, but exercising the real Validated&lt;T&gt; → Apply path.
    ///
    /// This golden is a SEPARATE file (<c>golden-applier-scenario.golden.txt</c>); the two existing goldens are
    /// NEVER re-recorded here. Re-baseline: <c>CHIMERA_GOLDEN_RECORD=1 dotnet test --filter FullyQualifiedName~GoldenApplier</c>,
    /// then <c>dotnet build</c> (refreshes the embedded copy) and commit. DO NOT hand-edit.
    /// </summary>
    public class GoldenApplierScenarioTests
    {
        /// <summary>
        /// Records the applier-driven golden and, in re-baseline mode (CHIMERA_GOLDEN_RECORD=1), writes it to the
        /// source file under Golden/. In normal mode it does NOT write — it only verifies the harness emits one
        /// sample per tick and that the sequence evolves over time (a constant sequence would mean the applier's
        /// scenario isn't exercising the systems).
        /// </summary>
        [Fact]
        public void RecordApplierGoldenBaseline()
        {
            var seq = GoldenChecksumReplay.RunAndRecord(GoldenApplierScenario.DefaultTicks,
                build: GoldenApplierScenario.Build);

            Assert.True(seq.Count >= GoldenApplierScenario.DefaultTicks,
                $"Expected >= {GoldenApplierScenario.DefaultTicks} checksum samples, got {seq.Count}.");

            // The sequence must CHANGE over time — proves the applied scenario actually exercises the systems.
            Assert.True(seq.Select(s => s.Hash).Distinct().Count() > 1,
                "Applier golden sequence is constant — the applied scenario is not exercising the systems.");

            // Re-baseline safety: never record a sequence a second in-process run can't reproduce, or one the
            // round-trip can't read back. Catch nondeterminism / format breakage AT record time.
            var seq2 = GoldenChecksumReplay.RunAndRecord(GoldenApplierScenario.DefaultTicks,
                build: GoldenApplierScenario.Build);
            Assert.True(seq.SequenceEqual(seq2),
                "Refusing to record: two in-process applier runs diverged — fix the nondeterminism before re-baselining.");
            Assert.True(
                GoldenChecksumReplay.ParseGolden(
                    System.Text.Encoding.UTF8.GetBytes(
                        GoldenChecksumReplay.FormatGolden(seq, GoldenApplierScenario.Header)))
                    .SequenceEqual(seq),
                "Refusing to record: FormatGolden/ParseGolden do not round-trip the recorded sequence.");

            bool wrote = GoldenChecksumReplay.MaybeRecord(seq, GoldenApplierScenario.GoldenFileName, GoldenApplierScenario.Header);
            if (wrote)
                Assert.True(GoldenChecksumReplay.IsRecordMode); // sanity: only writes in record mode
        }

        /// <summary>
        /// The committed applier golden was generated by a PRIOR process (the record run) and embedded at build
        /// time, so asserting a fresh process's run against it IS a cross-process determinism check. Also asserts
        /// two fresh in-process builds agree (no static/shared-state leak through the applier path).
        /// </summary>
        [Fact]
        public void ApplierDrivenRun_MatchesGolden_AndIsDeterministic()
        {
            if (GoldenChecksumReplay.IsRecordMode) return; // re-baseline run: golden is being rewritten; skip

            var seq1 = GoldenChecksumReplay.RunAndRecord(GoldenApplierScenario.DefaultTicks, build: GoldenApplierScenario.Build);
            var seq2 = GoldenChecksumReplay.RunAndRecord(GoldenApplierScenario.DefaultTicks, build: GoldenApplierScenario.Build);

            Assert.True(seq1.SequenceEqual(seq2),
                "Two in-process applier runs diverged — a static/shared mutable-state leak broke determinism.");

            var golden = GoldenChecksumReplay.LoadGolden(GoldenApplierScenario.GoldenFileName);
            var div = GoldenChecksumReplay.CompareSequences(golden, seq1);
            Assert.True(div is null, div is null ? "" : GoldenChecksumReplay.DescribeDivergence(div.Value));
        }
    }
}
