#nullable enable
using System.Linq;
using ProjectChimera.Core;
using Xunit;

namespace ProjectChimera.Sim.Tests.Golden
{
    /// <summary>
    /// Story 1.3a (AC3) — the multi-faction golden-checksum guard. Mirrors
    /// <see cref="GoldenChecksumReplayTests"/> but drives the 4-active-faction
    /// <see cref="MultiFactionScenario"/> through the SAME engine, proving the registry's active-faction span
    /// path is byte-deterministic in-process, reproduces a golden recorded by a prior process, and that a
    /// one-tick perturbation of a faction-3 entity's Fixed health is detected AND located.
    /// </summary>
    public class MultiFactionGoldenTests
    {
        private const string GoldenFile = "golden-multifaction.golden.txt";

        /// <summary>
        /// Records the multi-faction golden and, in re-baseline mode (CHIMERA_GOLDEN_RECORD=1), writes it to
        /// the source file under Golden/. In normal mode it does NOT write — it verifies the harness emits the
        /// expected number of samples and that the sequence actually evolves over time.
        ///
        /// Re-baseline (intentional behavior change only):
        ///   PowerShell: $env:CHIMERA_GOLDEN_RECORD=1; dotnet test godot/ProjectChimera.Sim.Tests --filter FullyQualifiedName~MultiFaction; Remove-Item Env:\CHIMERA_GOLDEN_RECORD
        ///   then: dotnet build (refreshes the embedded copy); git add the golden; commit.
        /// </summary>
        [Fact]
        public void RecordMultiFactionBaseline()
        {
            var seq = GoldenChecksumReplay.RunAndRecord(
                MultiFactionScenario.DefaultTicks, build: MultiFactionScenario.Build);

            // One sample per tick (ChecksumInterval = 1).
            Assert.True(seq.Count >= MultiFactionScenario.DefaultTicks,
                $"Expected >= {MultiFactionScenario.DefaultTicks} checksum samples, got {seq.Count}.");

            // The sequence must CHANGE over time — proves P1 (worker/melee/barracks) is exercising the systems.
            // (If this fails, an inert P3/P4 unit is probably drifting into combat — fix positioning/command,
            // NEVER the golden.)
            Assert.True(seq.Select(s => s.Hash).Distinct().Count() > 1,
                "Multi-faction golden sequence is constant — the scenario is not exercising the systems.");

            // Re-baseline safety gate (same as 1.2): never commit a golden a second in-process run can't
            // reproduce, or one ParseGolden can't read back.
            var seq2 = GoldenChecksumReplay.RunAndRecord(
                MultiFactionScenario.DefaultTicks, build: MultiFactionScenario.Build);
            Assert.True(seq.SequenceEqual(seq2),
                "Refusing to record: two in-process runs diverged — fix the nondeterminism before re-baselining.");
            Assert.True(
                GoldenChecksumReplay.ParseGolden(
                    System.Text.Encoding.UTF8.GetBytes(GoldenChecksumReplay.FormatGolden(seq)))
                    .SequenceEqual(seq),
                "Refusing to record: FormatGolden/ParseGolden do not round-trip the recorded sequence.");

            bool wrote = GoldenChecksumReplay.MaybeRecord(seq, GoldenFile);
            if (wrote)
                Assert.True(GoldenChecksumReplay.IsRecordMode); // sanity: only writes in record mode
        }

        /// <summary>
        /// AC3 — in-process determinism + golden match. Two FRESH 4-faction builds in one process produce
        /// byte-identical sequences (no static/shared mutable state), and both match the committed golden.
        /// </summary>
        [Fact]
        public void RunsTwiceInProcess_BothMatchGoldenAndEachOther()
        {
            if (GoldenChecksumReplay.IsRecordMode) return; // re-baseline run: golden is being rewritten; skip

            var seq1 = GoldenChecksumReplay.RunAndRecord(
                MultiFactionScenario.DefaultTicks, build: MultiFactionScenario.Build);
            var seq2 = GoldenChecksumReplay.RunAndRecord(
                MultiFactionScenario.DefaultTicks, build: MultiFactionScenario.Build);

            Assert.True(seq1.SequenceEqual(seq2),
                "Two in-process multi-faction runs diverged — a static/shared mutable-state leak broke determinism.");

            var golden = GoldenChecksumReplay.LoadGolden(GoldenFile);
            var div = GoldenChecksumReplay.CompareSequences(golden, seq1);
            Assert.True(div is null, div is null ? "" : GoldenChecksumReplay.DescribeDivergence(div.Value));
        }

        /// <summary>
        /// AC3 — cross-process reproduction. The committed golden was generated by a PRIOR process (the record
        /// run) and embedded at build time, so a fresh `dotnet test` process's run matching it IS the
        /// two-process comparison.
        /// </summary>
        [Fact]
        public void MatchesGolden_RecordedInSeparateProcess()
        {
            if (GoldenChecksumReplay.IsRecordMode) return; // re-baseline run: golden is being rewritten; skip

            var seq = GoldenChecksumReplay.RunAndRecord(
                MultiFactionScenario.DefaultTicks, build: MultiFactionScenario.Build);
            var golden = GoldenChecksumReplay.LoadGolden(GoldenFile);

            var div = GoldenChecksumReplay.CompareSequences(golden, seq);
            Assert.True(div is null, div is null ? "" : GoldenChecksumReplay.DescribeDivergence(div.Value));
        }

        /// <summary>
        /// AC3 — drift on the multi-faction scenario is detected AND located. Injecting +1 raw into the
        /// faction-3 inert unit's Fixed health at loop index K (it is never touched by combat, so the change
        /// persists) must make the harness FAIL with a divergence located at exactly tick K+1, expected != actual.
        /// </summary>
        [Fact]
        public void OneTickPerturbation_OfFaction3Entity_IsDetectedAndLocated()
        {
            if (GoldenChecksumReplay.IsRecordMode) return; // re-baseline run: skip

            const int k = 100;                                  // perturb at loop index 100 => tick 101
            Assert.True(MultiFactionScenario.DefaultTicks > k + 1,
                $"AC3 needs DefaultTicks ({MultiFactionScenario.DefaultTicks}) > k+1 ({k + 1}) so the perturbed tick is recorded.");
            int targetId = MultiFactionScenario.PerturbTargetId; // the Player3 inert unit

            var golden = GoldenChecksumReplay.LoadGolden(GoldenFile);
            var perturbed = GoldenChecksumReplay.RunAndRecord(
                MultiFactionScenario.DefaultTicks,
                perturb: (i, w) =>
                {
                    if (i == k)
                        w.Health[targetId] = Fixed.FromRaw(w.Health[targetId].Raw + 1);
                },
                build: MultiFactionScenario.Build);

            var div = GoldenChecksumReplay.CompareSequences(golden, perturbed);

            Assert.True(div is not null, "Perturbation went undetected — the guard does not actually guard!");
            Assert.Equal((uint)(k + 1), div!.Value.Tick);
            Assert.NotEqual(div.Value.Expected, div.Value.Actual);
        }
    }
}
