#nullable enable
using System.Linq;
using ProjectChimera.Core;
using Xunit;

namespace ProjectChimera.Sim.Tests.Golden
{
    /// <summary>
    /// Story 1.9a (AC2, D11) — the cross-faction same-tick tie-break regression guard (AR-40 fork #1). Runs a
    /// symmetric Player1-vs-Player2 same-tick melee engagement (<see cref="SameTickTieBreakScenario"/>) and pins
    /// the per-tick SimChecksum sequence, so the ascending-faction-slot (today ascending-entity-ID) resolution
    /// order is proven deterministic in-process AND reproducible across processes (the committed golden was
    /// recorded by a PRIOR process and embedded at build time). A divergence is a genuine same-tick
    /// non-determinism bug — fix it and re-baseline ONLY this golden, never the other three.
    /// </summary>
    public class SameTickTieBreakGoldenTests
    {
        [Fact]
        public void RecordTieBreakGoldenBaseline()
        {
            var seq = GoldenChecksumReplay.RunAndRecord(SameTickTieBreakScenario.DefaultTicks,
                build: SameTickTieBreakScenario.Build);

            Assert.True(seq.Count >= SameTickTieBreakScenario.DefaultTicks,
                $"Expected >= {SameTickTieBreakScenario.DefaultTicks} checksum samples, got {seq.Count}.");

            // The sequence must CHANGE over time — proves the duel actually mutates hashed state (Health/deaths).
            Assert.True(seq.Select(s => s.Hash).Distinct().Count() > 1,
                "Tie-break golden sequence is constant — the duel is not exercising combat.");

            // Re-baseline safety: never record a sequence a second in-process run can't reproduce, or one the
            // round-trip can't read back. Catch nondeterminism / format breakage AT record time.
            var seq2 = GoldenChecksumReplay.RunAndRecord(SameTickTieBreakScenario.DefaultTicks,
                build: SameTickTieBreakScenario.Build);
            Assert.True(seq.SequenceEqual(seq2),
                "Refusing to record: two in-process tie-break runs diverged — fix the same-tick nondeterminism first.");
            Assert.True(
                GoldenChecksumReplay.ParseGolden(
                    System.Text.Encoding.UTF8.GetBytes(
                        GoldenChecksumReplay.FormatGolden(seq, SameTickTieBreakScenario.Header)))
                    .SequenceEqual(seq),
                "Refusing to record: FormatGolden/ParseGolden do not round-trip the recorded sequence.");

            bool wrote = GoldenChecksumReplay.MaybeRecord(seq, SameTickTieBreakScenario.GoldenFileName,
                SameTickTieBreakScenario.Header);
            if (wrote)
                Assert.True(GoldenChecksumReplay.IsRecordMode); // sanity: only writes in record mode
        }

        /// <summary>
        /// The committed tie-break golden was generated by a PRIOR process (the record run) and embedded at build
        /// time, so asserting a fresh process's run against it IS a cross-process determinism / order-stability
        /// check. Also asserts two fresh in-process builds agree (no static/shared-state leak).
        /// </summary>
        [Fact]
        public void SameTickEngagement_MatchesGolden_AndIsOrderStable()
        {
            if (GoldenChecksumReplay.IsRecordMode) return; // re-baseline run: golden is being rewritten; skip

            var seq1 = GoldenChecksumReplay.RunAndRecord(SameTickTieBreakScenario.DefaultTicks, build: SameTickTieBreakScenario.Build);
            var seq2 = GoldenChecksumReplay.RunAndRecord(SameTickTieBreakScenario.DefaultTicks, build: SameTickTieBreakScenario.Build);

            Assert.True(seq1.SequenceEqual(seq2),
                "Two in-process same-tick runs diverged — the cross-faction resolution order is not deterministic.");

            var golden = GoldenChecksumReplay.LoadGolden(SameTickTieBreakScenario.GoldenFileName);
            var div = GoldenChecksumReplay.CompareSequences(golden, seq1);
            Assert.True(div is null, div is null ? "" : GoldenChecksumReplay.DescribeDivergence(div.Value));
        }
    }
}
